# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 19:57
from __future__ import unicode_literals

import apis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRezdy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', apis.models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
