# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-23 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_importrezdy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImportRezdy',
            new_name='Rezdy',
        ),
    ]
