# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-24 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20180423_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezdy',
            name='data',
        ),
    ]
